// src/components/navbar/navbar.tsx
import { component$, useSignal } from '@builder.io/qwik';
import { Link } from '@builder.io/qwik-city';

export const NavBar = component$(() => {
    const isMenuActive = useSignal(false);

    const navItems = [
        { id: 1, title: 'Home', path: '/' },
        { id: 2, title: 'Browse', path: '/browse' },
        { id: 3, title: 'Contact', path: '/contact' },
    ];

    return (
        <>
            <header class="display:flex gap:1rem align-items:center justify-content:space-between">
                <div>
                    <img src="" alt="logo" width={150} height={50} class="margin:2rem" />
                </div>

                <button
                    class="color:$text display:none border:0 maxw35em:display:block maxw35em:background-color:transparent maxw35em:background-image:url(/menu.svg) maxw35em:background-repeat:no-repeat maxw35em:position:absolute maxw35em:z-index:9999 maxw35em:width:2rem maxw35em:aspect-ratio:1 maxw35em:top:2rem maxw35em:right:2rem"
                    aria-controls="primary-navigation"
                    aria-expanded={`${isMenuActive.value}`}
                    onClick$={() => (isMenuActive.value = !isMenuActive.value)}
                >
                    <span class="sr-only">Menu</span>
                </button>

                <nav class="">
                    <ul
                        class="display:flex gap:1rem list-style:none background:$background maxw35em:gap:3em maxw35em:position:fixed maxw35em:z-index:1000 maxw35em:inset:0_0_0_30%  maxw35em:flex-direction:column maxw35em:padding:min(30vh,10rem)_2em [[data-visible=^false^]]{maxw35em:transform:translateX(100%)} [[data-visible=^true^]]{maxw35em:transform:translateX(0%)}"
                        id="primary-navigation"
                        data-visible={`${isMenuActive.value}`}
                    >
                        {navItems.map((item) => (
                            <li key={item.id}>
                                <Link class="text-decoration:none" href={item.path}>
                                    {' '}
                                    {item.title}
                                </Link>
                            </li>
                        ))}
                    </ul>
                </nav>
            </header>
        </>
    );
});

// src/Components/Navbar.svelte
<script lang="ts">
  import { page } from "$app/stores";

  let active: boolean = false;
  const toggleButton = async () => {
    active = !active;
  };

  const nav = [
    { title: "Home", path: "/" },
    { title: "Browse", path: "/browse" },
    { title: "Contact", path: "/contact" },
  ];
</script>

<nav class="navbar">
  <div class="brand-title" />
  <a href="#" class="toggle-button" on:click={toggleButton}>
    <span class="bar" />
    <span class="bar" />
    <span class="bar" />
  </a>
  <div class="navbar-links" class:active>
    <ul>
      {#each nav as item}
        <li>
          <a href={item.path}>{item.title}</a>
        </li>
      {/each}
    </ul>
  </div>
</nav>

<style>
  .navbar {
    display: flex;
    justify-content: space-between;
    align-items: center;
    background-color: var(--primary-color);
    color: var(--primary-text-color);
  }

  .navbar-links ul {
    display: flex;
  }

  .navbar-links li {
    list-style: none;
  }

  .navbar-links li a {
    text-decoration: none;
    color: var(--primary-text-color);
    padding: 1rem;
    display: block;
  }

  .navbar-links li a:hover {
    color: var(--accent-color);
  }

  .toggle-button {
    position: absolute;
    top: 0.75rem;
    right: 1rem;
    display: none;
    flex-direction: column;
    justify-content: space-between;
    width: 31px;
    height: 21px;
  }

  .toggle-button .bar {
    height: 3px;
    width: 100%;
    background-color: var(--primary-text-color);
    border-radius: 10px;
  }

  @media (max-width: 650px) {
    .toggle-button {
      display: flex;
    }

    .navbar-links {
      display: none;
      width: 100%;
    }

    .navbar {
      flex-direction: column;
      align-items: flex-start;
    }

    .navbar-links ul {
      width: 100%;
      flex-direction: column;
    }

    .navbar-links li {
      text-align: center;
    }

    .navbar-links li a {
      padding: 0.5rem 1rem;
    }

    .navbar-links.active {
      display: flex;
    }
  }
</style>
