// src/components/storecard/storecard.tsx
import { component$, useResource$, Resource } from '@builder.io/qwik';
import { StoreDeal } from '../storedeal/storedeal';
import type GameDeal from '~/interfaces/GameDeal';
import { Image } from '@unpic/qwik';

interface ItemProps {
    storeId: string;
    storeName: string;
}

export const StoreCard = component$<ItemProps>((props) => {
    const gameDeals = useResource$<GameDeal[]>(async ({ cleanup }) => {

        const controller = new AbortController();
        cleanup(() => controller.abort());

        const response = await fetch(
            `https://www.cheapshark.com/api/1.0/deals?storeID=${props.storeId}&pageSize=7`, {
                signal: controller.signal,
                headers: {
                    'Cache-Control': 'max-age=300'
                }
            }
        );

        if (!response.ok) {
            controller.abort();
        }

        const data = await response.json();

        return data as GameDeal[];
    });

    return (
        <>
            <div class="border:1px_solid_#ccc margin-bottom:50px">
                <div class="text-align:center padding:25px_10px background-color:$background-lighten-10 color:$text">
                    <Image
                        class="display:inline max-width:100% max-height:100%"
                        layout="constrained"
                        src={`https://www.cheapshark.com/img/stores/logos/${Number(props.storeId) - 1}.png`}
                        alt={props.storeName}
                        width={64}
                        height={64}
                    />
                </div>
                <div class="padding:30px_10px text-align:center font-size:$fontSize300 background-color:$background">
                    <Resource
                        value={gameDeals}
                        onPending={() => <p>Loading....</p>}
                        onRejected={() => <p>Failed to load data</p>}
                        onResolved={(deals) => (
                            <>
                                {deals.map((deal) => (
                                    <StoreDeal
                                    key={deal.dealID}
                                    dealID={deal.dealID}
                                    isOnSale={deal.isOnSale}
                                    normalPrice={deal.normalPrice}
                                    salePrice={deal.salePrice}
                                    title={deal.title}  />
                                ))}
                            </>
                        )}
                    />
                    <a href={`/browse?storeID=${props.storeId}`} class="display:block color:$text text-align:center background-color:$background text-decoration:none margin-top:30px padding:10px_5px hover:color:$accent">
                        View all deals
                    </a>
                </div>
            </div>
        </>
    );
});

// src/Components/StoreCard.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import StoreDeal from '../Components/StoreDeal.svelte';

	export let storeData: any;

	$: storeDeals = [];

	onMount(async () => {
		const url = `https://www.cheapshark.com/api/1.0/deals?storeID=${storeData.storeID}&pageSize=7`;
		const res = await fetch(url);
		storeDeals = res.ok && (await res.json());
	});
</script>

<div class="card">
	<div class="card-header">
		<img
			src="https://www.cheapshark.com/img/stores/banners/{storeData.storeID - 1}.png"
			alt={storeData.storeName}
			height="50"
		/>
	</div>
	<div class="card-body">
		{#each storeDeals as deal}
			<StoreDeal dealData={deal} />
		{:else}
			Loading....
		{/each}
		<a href="/browse?storeID={storeData.storeID}" class="btn">View all deals</a>
	</div>
</div>

<style>
	.card {
		background-color: #fff;
		border: 1px solid #ccc;
		margin-bottom: 50px;
		transition: 0.3s;
	}

	.card-header {
		text-align: center;
		padding: 25px 10px;
		background-color: var(--secondary-color);
		color: #fff;
	}

	.card-header > img {
		max-width: 100%;
		max-height: 100%;
	}

	.card-body {
		padding: 30px 10px;
		text-align: center;
		font-size: 14px;
		background-color: var(--tertiary-color);
	}

	.card-body .btn {
		display: block;
		color: #fff;
		text-align: center;
		background: var(--secondary-color);
		text-decoration: none;
		margin-top: 30px;
		padding: 10px 5px;
		transition: 0.3s;
	}

	.card-body .btn:hover {
		transform: scale(1.04);
		color: var(--accent-color);
	}
</style>
