// src/components/storedeal/storedeal.tsx
import { component$ } from '@builder.io/qwik';

interface ItemProps {
    dealID: string;
    title: string;
    isOnSale: string;
    salePrice: string;
    normalPrice: string;
}

export const StoreDeal = component$<ItemProps>((props) => {
    const cheapSharkRedirectLink = 'https://www.cheapshark.com/redirect?dealID=';
    const MAX_GAME_TITLE_LENGTH = 18;

    function truncateString(str: string, num: number) {
        if (str.length > num) {
            return str.slice(0, num) + '...';
        } else {
            return str;
        }
    }

    return (
        <>
            <div class="display:flex flex-direction:row flex-wrap:nowrap justify-content:space-between margin:25px_0px [div]{text-align:left;padding:0px_10px}">
                <div class="game-title">
                    <a
                        class="text-decoration:none color:$text hover:color:$accent font-size:$fontSize300"
                        href={cheapSharkRedirectLink + props.dealID}
                        target="_blank"
                        rel="noreferrer"
                    >
                        {truncateString(props.title, MAX_GAME_TITLE_LENGTH)}
                    </a>
                </div>
                <div>
                    {props.isOnSale === '1' && <s>${props.normalPrice}</s>}

                    <span class="color:$text_!important background-color:$primary padding:3px border:1px_solid_$text border-radius:5px margin-left:5px font-weight:700">${props.salePrice}</span>
                </div>
            </div>
        </>
    );
});

// src/Components/StoreDeal.svelte
<script lang="ts">
  export let dealData: any;

  let cheapSharkRedirectLink = "https://www.cheapshark.com/redirect?dealID=";
  const MAX_GAME_TITLE_LENGTH = 22;

  function truncateString(str: string, num: number) {
    if (str.length > num) {
      return str.slice(0, num) + "...";
    } else {
      return str;
    }
  }
</script>

<div class="deal-container">
  <div class="game-title">
    <a href={cheapSharkRedirectLink + dealData.dealID} target="_blank"
      >{truncateString(dealData.title, MAX_GAME_TITLE_LENGTH)}</a
    >
  </div>
  <div class="prices">
    {#if dealData.isOnSale === "1"}
      <s>${dealData.normalPrice}</s>
    {/if}

    <span class="price-highlight">${dealData.salePrice}</span>
  </div>
</div>

<style>
  .deal-container {
    display: flex;
    flex-direction: row;
    flex-wrap: nowrap;
    justify-content: space-between;
    margin: 25px 0px;
  }

  .game-title a {
    text-decoration: underline;
    text-decoration-style: dotted;
    color: #000;
  }

  .game-title a:hover {
    color: var(--accent-color);
  }

  .deal-container > div {
    text-align: left;
    padding: 0px 10px;
  }

  .price-highlight {
    color: var(--secondary-text-color) !important;
    background-color: var(--accent-color);
    padding: 3px;
    border: 1px solid #909090;
    border-radius: 5px;
    margin-left: 5px;
    font-weight: bold;
  }
</style>
