// src/routes/policy/+page.svelte
<svelte:head>
	<title>CheaplyGames - Privacy Policy</title>
	<meta name="description" content="CheaplyGames's privacy policy">
</svelte:head>

<div class="content">
	<iframe
		src="https://www.termsfeed.com/live/02601daa-defe-4998-a6c2-2f99d9543dfe"
		frameborder="0"
		title="Privacy Policy"
	/>
</div>

<style>
	.content {
		max-width: 1220px;
		padding: 15px 0;
		margin: 5px auto;
		border-radius: 15px;
		background: var(--tertiary-color);
		border: 1px solid #123;
		box-shadow: 0 3px 20px #11110f;
		min-height: 550px;
	}

	.content iframe {
		border: none;
		width: 99%;
		height: 1000px;
	}
</style>

// src/routes/policy/index.tsx
import { component$, useStylesScoped$ } from '@builder.io/qwik';
import styles from './policy.css?inline';
import type { DocumentHead } from '@builder.io/qwik-city';

export default component$(() => {
    useStylesScoped$(styles);
    return (
        <>
            <div class="content">
                <iframe
                    src="https://www.termsfeed.com/live/02601daa-defe-4998-a6c2-2f99d9543dfe"
                    title="Privacy Policy"
                />
            </div>
        </>
    );
});

export const head: DocumentHead = {
    title: 'CheaplyGames - Privacy Policy',
    meta: [
        {
            name: 'description',
            content: "CheaplyGames's privacy policy",
        },
    ],
};
