// src/routes/contact/index.tsx
import { component$ } from '@builder.io/qwik';
import { type DocumentHead, routeLoader$, z } from '@builder.io/qwik-city';
import type { InitialValues } from '@modular-forms/qwik';
import { formAction$, useForm, zodForm$ } from '@modular-forms/qwik';
import { FeedbackMessage } from '~/components/feedbackmessage/feedbackmessage';

const contactSchema = z.object({
    name: z.string().min(1, 'Please enter your name.'),
    email: z
        .string()
        .min(1, 'Please enter your email.')
        .email('Invalid email address format. (example@mail.com)'),
    message: z.string().min(1, 'Please enter your message.'),
});

type ContactForm = z.infer<typeof contactSchema>;

export const useFormLoader = routeLoader$<InitialValues<ContactForm>>(() => ({
    name: '',
    email: '',
    message: '',
}));

export const useFormAction = formAction$<ContactForm>(async (values, { env }) => {
    const response = await fetch('https://mazi.ro/contact-submit.php', {
        method: 'POST',
        headers: { 'Content-type': 'application/x-www-form-urlencoded' },
        body: `name=${values.name}&email=${values.email}&message=${
            values.message
        }&myEmail=${env.get('PRIVATE_EMAIL')}`,
    });

    if (!response.ok) {
        return { status: 'error', message: 'An error has occurred!' };
    }

    return { status: 'success', message: 'Contact form successfully submitted!' };
}, zodForm$(contactSchema));

export default component$(() => {
    const [contactForm, { Form, Field }] = useForm<ContactForm>({
        loader: useFormLoader(),
        action: useFormAction(),
        validate: zodForm$(contactSchema),
        validateOn: 'change',
    });

    return (
        <>
            <Form
                class="background:$secondary width:50rem margin:50px_auto max-width:97% border-radius:4px padding:55px_30px"
                id="contact-form"
            >
                {contactForm.submitted && (
                    <FeedbackMessage
                        status={contactForm.response?.status}
                        messasge={contactForm.response?.message}
                    />
                )}
                <div>
                    <h1 class="font-size:$fontSize500 letter-spacing:6px border-bottom:1px_solid_$text display:inline-block padding-bottom:8px margin-bottom:32px color:$text">
                        CONTACT US
                    </h1>
                </div>
                <div class="display:flex justify-content:space-between maxw40em:flex-direction:column">
                    <Field name="name">
                        {(field, props) => (
                            <div class="display:flex flex-direction:column margin-bottom:24px width:48% maxw40em:width:100%">
                                <label class="display:block font-size:$fontSize300 letter-spacing:0.2em margin-bottom:16px color:$text" for={field.name}>NAME</label>
                                <input
                                    {...props}
                                    type="text"
                                    id={field.name}
                                    value={field.value}
                                    required
                                    class="border-radius:4px border:1px_solid_$text outline:0 padding:16px width:100% height:44px background:$background"
                                />
                                {field.error && <div class="color:$text font-size:$fontSize300">{field.error}</div>}
                            </div>
                        )}
                    </Field>
                    <Field name="email">
                        {(field, props) => (
                            <div class="display:flex flex-direction:column margin-bottom:24px width:48% maxw40em:width:100%">
                                <labe class="display:block font-size:$fontSize300 letter-spacing:0.2em margin-bottom:16px color:$text" for={field.name}>EMAIL</labe>
                                <input
                                    {...props}
                                    type="email"
                                    id={field.name}
                                    value={field.value}
                                    required
                                    class="border-radius:4px border:1px_solid_$text outline:0 padding:16px width:100% height:44px background:$background"
                                />
                                {field.error && <div class="color:$text font-size:$fontSize300">{field.error}</div>}
                            </div>
                        )}
                    </Field>
                </div>
                <div>
                    <Field name="message">
                        {(field, props) => (
                            <div class="margin-bottom:24px">
                                <label class="display:block font-size:$fontSize300 letter-spacing:0.2em margin-bottom:16px color:$text" for={field.name}>Message</label>
                                <textarea
                                    {...props}
                                    id={field.name}
                                    value={field.value}
                                    required
                                    class="border-radius:4px border:1px_solid_$text outline:0 padding:12px_16px width:100% height:200px background:$background"
                                />
                                {field.error && <div class="color:$text font-size:$fontSize300">{field.error}</div>}
                            </div>
                        )}
                    </Field>
                </div>
                <div class="margin-bottom:32px maxw40em:display:flex maxw40em:flex-direction:column">
                    <input type="submit" value="SEND MESSAGE" class="border-radius:4px border:1px_solid_$text cursor:pointer font-weight:600 height:44px letter-spacing:0.1em outline:0 padding:0_20px_0_22px margin-right:10px background:$accent color:$secondary maxw40em:margin-bottom:10px maxw40em:width:100%" />
                </div>
            </Form>
        </>
    );
});

export const head: DocumentHead = {
    title: 'CheaplyGames - Contact',
    meta: [
        {
            name: 'description',
            content: 'Contact us page for CheaplyGames',
        },
    ],
};

// pages/contact.vue
<script setup>
import { useForm } from '@formwerk/core';

useHead({
	title: 'CheaplyGames - Contact',
	meta: [
		{name: 'description', content: 'Contact us page for CheaplyGames'}
	]
});

const runtimeConfig = useRuntimeConfig();

const name = ref('');
const email = ref('');
const message = ref('');

const { handleSubmit, isSubmitting, wasSubmitted } = useForm();

const onSubmit = handleSubmit(async (data) => {
	const json = data.toObject();

	await $fetch('https://mazi.ro/contact-submit.php', {
		method: 'POST',
		headers: { 'Content-type': 'application/x-www-form-urlencoded' },
		body: `name=${json.name}&email=${json.email}&message=${json.message}&myEmail=${runtimeConfig.public.PRIVATE_EMAIL}`
	});

});
</script>

<template>

	<div>
		<form v-if="!wasSubmitted" method="POST" @submit="onSubmit">

			<div>
				<h1>CONTACT US</h1>
			</div>

			<div class="form-wrapper">
				<div class="field-wrapper">
					<TextField
v-model="name" label="Your name" name="name" placeholder="John Doe" type="text"
						required />
				</div>

				<div class="field-wrapper">
					<TextField
v-model="email" label="Your email" name="email" placeholder="example@mail.com"
						type="email" required />
				</div>
			</div>

			<div class="wrapper-textarea">
				<TextAreaField v-model="message" label="Your message" name="message" required />
			</div>

			<div class="button">
				<button :disabled="isSubmitting" type="submit">SEND MESSAGE</button>
			</div>
		</form>

		<h1 v-else class="center">Submission successful!</h1>
	</div>



</template>

<style scoped>
form {
	background: var(--secondary);
	width: 50rem;
	margin: 50px auto;
	max-width: 97%;
	border-radius: 4px;
	padding: 55px 30px;
}

h1 {
	font-size: var(--fontSize500);
	letter-spacing: 6px;
	border-bottom: 1px solid var(--text);
	display: inline-block;
	padding-bottom: 8px;
	margin-bottom: 32px;
	color: var(--text);
}

.center {
	text-align: center;
	margin: 0 auto;
	display: block;
}

label {
	display: block;
	font-size: var(--fontSize300);
	letter-spacing: 0.2em;
	margin-bottom: 16px;
	color: var(--text);
}

input,
textarea {
	border-radius: 4px;
	border: 1px solid var(--text);
	outline: 0;
	padding: 16px;
	width: 100%;
	height: 44px;
	background: var(--background);
}

textarea {
	padding: 12px 16px;
	height: 200px;
	background: var(--background);
}

button {
	border-radius: 4px;
	border: 1px solid var(--text);
	cursor: pointer;
	font-weight: 600;
	height: 44px;
	letter-spacing: 0.1em;
	outline: 0;
	padding: 0 20px 0 22px;
	margin-right: 10px;
	background: var(--accent);
	color: var(--secondary);
}

.field-wrapper {
	display: flex;
	flex-direction: column;
	margin-bottom: 24px;
	width: 48%;
}

.form-wrapper {
	display: flex;
	justify-content: space-between;
}

.wrapper-textarea {
	margin-bottom: 24px;
}

.button {
	margin-bottom: 32px;
}

@media screen and (max-width: 40em) {
	button {
		margin-bottom: 10px;
		width: 100%;
	}

	.form-wrapper {
		flex-direction: column;
	}

	.wrapper {
		width: 100%;
	}
}
</style>
